[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.145.0"  # Use the version you're using locally

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
